[package]
name = "solidity-frontend"
version = "0.1.0"
authors = ["Agustin Chiappe Berrini <jnieve@gmail.com>"]
edition = "2018"

[lib]
name = "solidity_frontend"
path = "src/lib.rs"

[dependencies]
failure = "0.1.3"
llvm-sys = "70"
nom = "4.2.3"
